[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = "simpnmr/__version__.py:__version__"
version_source = "tag"
branch = "main"
hvcs = "gitlab"

upload_to_pypi = true
upload_to_repository = true

build_command = "python -m build"